chore: use dev mode

diff --git a/packages/sshnoports/scripts/install_sshnpd b/packages/sshnoports/scripts/install_sshnpd
--- a/packages/sshnoports/scripts/install_sshnpd
+++ b/packages/sshnoports/scripts/install_sshnpd
@@ -194,31 +194,39 @@ make_dirs() {
 }
 
 download() {
-  if [ -n "$SSHNP_LOCAL" ]; then
-    echo "DEV MODE: Installing using local $EXT file: $SSHNP_LOCAL";
-    cp "$SSHNP_LOCAL" "$HOME_PATH/.atsign/temp/$BINARY_NAME.$EXT";
-  else
-    echo "Downloading $BINARY_NAME from $DOWNLOAD";
-    curl -sL "$DOWNLOAD" -o "$HOME_PATH/.atsign/temp/$BINARY_NAME.$EXT";
-  fi
+  if [ -z "$SSHNP_DEV_MODE" ]; then
+    if [ -n "$SSHNP_LOCAL" ]; then
+      echo "DEV MODE: Installing using local $EXT file: $SSHNP_LOCAL";
+      cp "$SSHNP_LOCAL" "$HOME_PATH/.atsign/temp/$BINARY_NAME.$EXT";
+    else
+      echo "Downloading $BINARY_NAME from $DOWNLOAD";
+      curl -sL "$DOWNLOAD" -o "$HOME_PATH/.atsign/temp/$BINARY_NAME.$EXT";
+    fi
 
-  if [ ! -f "$HOME_PATH/.atsign/temp/$BINARY_NAME.$EXT" ]; then
-    echo "Failed to download $BINARY_NAME";
-    exit 1;
-  fi
+    if [ ! -f "$HOME_PATH/.atsign/temp/$BINARY_NAME.$EXT" ]; then
+      echo "Failed to download $BINARY_NAME";
+      exit 1;
+    fi
 
-  case "$EXT" in
-    zip)
-      unzip -qo "$HOME_PATH/.atsign/temp/$BINARY_NAME.$EXT" -d "$HOME_PATH/.atsign/temp/";
-      ;;
-    tgz|tar.gz)
-      tar -zxf "$HOME_PATH/.atsign/temp/$BINARY_NAME.$EXT" -C "$HOME_PATH/.atsign/temp/";
-      ;;
-  esac
-  mv "$HOME_PATH/.atsign/temp/sshnp" "$HOME_PATH/.atsign/temp/$BINARY_NAME"; # Rename the extracted folder
+    case "$EXT" in
+      zip)
+        unzip -qo "$HOME_PATH/.atsign/temp/$BINARY_NAME.$EXT" -d "$HOME_PATH/.atsign/temp/";
+        ;;
+      tgz|tar.gz)
+        tar -zxf "$HOME_PATH/.atsign/temp/$BINARY_NAME.$EXT" -C "$HOME_PATH/.atsign/temp/";
+        ;;
+    esac
+    mv "$HOME_PATH/.atsign/temp/sshnp" "$HOME_PATH/.atsign/temp/$BINARY_NAME"; # Rename the extracted folder
+  fi
 
   if [ -n "$SSHNP_DEV_MODE" ]; then
     echo "DEV MODE: Installing from local repo: $SSHNP_DEV_MODE";
+    dart compile exe "$SSHNP_DEV_MODE/bin/sshnp.dart" -o "$HOME_PATH/.atsign/temp/$BINARY_NAME/sshnp";
+    dart compile exe "$SSHNP_DEV_MODE/bin/sshnpd.dart" -o "$HOME_PATH/.atsign/temp/$BINARY_NAME/sshnpd";
+    dart compile exe "$SSHNP_DEV_MODE/bin/sshrv.dart" -o "$HOME_PATH/.atsign/temp/$BINARY_NAME/sshrv";
+    dart compile exe "$SSHNP_DEV_MODE/bin/sshrvd.dart" -o "$HOME_PATH/.atsign/temp/$BINARY_NAME/sshrvd";
+    dart compile exe "$SSHNP_DEV_MODE/bin/activate_cli.dart" -o "$HOME_PATH/.atsign/temp/$BINARY_NAME/at_activate";
+
     cp -R "$SSHNP_DEV_MODE/templates/" "$HOME_PATH/.atsign/temp/$BINARY_NAME/templates/";
     cp "$SSHNP_DEV_MODE"/scripts/* "$HOME_PATH/.atsign/temp/$BINARY_NAME";
   fi
