refactor: sshnpd installer

diff --git a/packages/sshnoports/scripts/install_sshnpd b/packages/sshnoports/scripts/install_sshnpd
--- a/packages/sshnoports/scripts/install_sshnpd
+++ b/packages/sshnoports/scripts/install_sshnpd
@@ -2,6 +2,7 @@
 
 BINARY_NAME="sshnpd";
 
+# Prepend an @ to the front of the atsign if missing
 norm_atsign() {
   KEY="$1" # Get the variable name
   INPUT=${!KEY} # Get the value of the variable
@@ -11,7 +12,10 @@ norm_atsign() {
   export "${KEY}"="$ATSIGN" # Set the variable to new value
 }
 
-norm_version() {
+# Normalize a version string to tags/vX.X.X
+# This is strictly used for formatting the download URL
+# Don't use this for formatting user-facing output
+norm_to_tag_version() {
   KEY="$1" # Get the variable name
   INPUT=${!KEY} # Get the value of the variable
   shopt -s extglob
@@ -21,6 +25,7 @@ norm_version() {
   export "${KEY}"="tags/v$OUTPUT" # Add full tags/v prefix
 }
 
+# Print the usage information
 usage() {
   echo "Usage: $0 [options]"
   echo "General options:"
@@ -29,6 +34,8 @@ usage() {
   echo "  -l, --local <path>          Install using local zip/tgz"
   echo "  -r, --repo <path>           Install using local repo"
   echo "  -h, --help                  Display this help message"
+  # Intentionally hidden argument used for debugging
+  # echo "      --cache-temp            Keep the temporary cache created by this script"
   echo ""
   echo "Installation options:"
   echo "  -c, --client <address>      Client address (e.g. @alice_client)"
@@ -41,6 +48,7 @@ usage() {
   echo "  -n, --name <device name>    New name of the device"
 }
 
+# Parse the command-line args
 parse_args() {
   SSHNP_OP="install"
   while [ $# -gt 0 ]; do
@@ -51,6 +59,10 @@ parse_args() {
       ;;
       --rename)
         SSHNP_OP="rename"
+        shift 1
+      ;;
+      --cache-temp)
+        SSHNP_CACHE_TEMP=1
         shift 1
       ;;
       -h|--help)
@@ -111,7 +123,10 @@ parse_args() {
       ;;
     esac
   done
+}
 
+# Prompt for any missing but required arguments
+validate_args() {
   case "$SSHNP_OP" in
     install|rename)
       if [ -z "$CLIENT_ATSIGN" ]; then
@@ -139,6 +154,31 @@ parse_args() {
   esac
 }
 
+# Load requirements statuses into variables
+parse_requirements() {
+  REQ_CURL=$(command -v curl)
+  REQ_CRON=$(command -v crontab)
+  REQ_TMUX=$(command -v tmux)
+  REQ_LOGR=$(command -v logrotate)
+}
+
+# Check the script's requirements
+check_requirements() {
+  if [ -z "$REQ_CURL" ] && [ -z "$SSHNP_DEV_MODE" ] && [ -z "$SSHNP_LOCAL" ]; then
+    echo "  [X] Missing required dependency: curl"
+  fi
+  if [ -z "$REQ_CRON" ]; then
+    echo "  [X] Missing required dependency: cron"
+  fi
+  if [ -z "$REQ_TMUX" ] && [ -z "$REQ_LOGR" ]; then
+    echo "  [X] Missing required dependency"
+    echo "      One of the following dependencies must be installed:"
+    echo "        - tmux"
+    echo "        - logrotate"
+  fi
+}
+
+# Parse the system environment
 parse_env() {
   if [ -z "$SSHNP_USER" ]; then
     SSHNP_USER="$USER";
@@ -148,7 +188,7 @@ parse_env() {
   if [ -z "$SSHNP_VERSION" ]; then
     SSHNP_VERSION="latest";
   else
-    norm_version SSHNP_VERSION
+    norm_to_tag_version SSHNP_VERSION
   fi
   URL="https://api.github.com/repos/atsign-foundation/sshnoports/releases/$SSHNP_VERSION";
 
@@ -185,8 +225,10 @@ parse_env() {
     exit 1;
   fi
 
-  DOWNLOADS=$(curl -s "$URL" | grep browser_download_url | cut -d\" -f4);
-  DOWNLOAD=$(echo "$DOWNLOADS" | grep "$PLATFORM" | grep "$ARCH" | cut -d\" -f4)
+  if [ -z "$SSHNP_LOCAL" ] && [ -z "$SSHNP_DEV_MODE" ]; then
+    DOWNLOADS=$(curl -s "$URL" | grep browser_download_url | cut -d\" -f4);
+    DOWNLOAD=$(echo "$DOWNLOADS" | grep "$PLATFORM" | grep "$ARCH" | cut -d\" -f4)
+  fi
 
   if [ -n "$SSHNP_DEV_MODE" ]; then
     TEMP_PATH=$(date +%s);
@@ -197,10 +239,14 @@ parse_env() {
   fi
 }
 
+# Remove the temporary folder generated for processing the download/install
 cleanup() {
-  rm -rf "$HOME_PATH/.atsign/temp/$TEMP_PATH";
+  if [ -z "$SSHNP_CACHE_TEMP" ]; then
+    rm -rf "$HOME_PATH/.atsign/temp/$TEMP_PATH";
+  fi
 }
 
+# Make the necessary directories for sshnpd
 make_dirs() {
   rm -rf "$HOME_PATH/.atsign/temp/$TEMP_PATH";
   mkdir -p "$HOME_PATH/.ssh/" \
@@ -215,31 +261,51 @@ make_dirs() {
   fi
 }
 
-download() {
-  if [ -z "$SSHNP_DEV_MODE" ]; then
-    if [ -n "$SSHNP_LOCAL" ]; then
-      echo "DEV MODE: Installing using local $EXT file: $SSHNP_LOCAL";
-      cp "$SSHNP_LOCAL" "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME.$EXT";
+# Build the dart binaries from the provided repo
+build_dart_binaries() {
+  echo "DEV MODE: Installing from local repo: $SSHNP_DEV_MODE";
+    mkdir -p "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME/templates/"
+
+    cp -R "$SSHNP_DEV_MODE"/packages/sshnoports/templates/* "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME/templates/";
+    cp "$SSHNP_DEV_MODE"/packages/sshnoports/scripts/* "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME";
+
+    dart pub get -C "$SSHNP_DEV_MODE/packages/sshnoports"
+
+    dart compile exe "$SSHNP_DEV_MODE/packages/sshnoports/bin/sshnp.dart" -o "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME/sshnp";
+    dart compile exe "$SSHNP_DEV_MODE/packages/sshnoports/bin/sshnpd.dart" -o "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME/sshnpd";
+    dart compile exe "$SSHNP_DEV_MODE/packages/sshnoports/bin/sshrv.dart" -o "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME/sshrv";
+    dart compile exe "$SSHNP_DEV_MODE/packages/sshnoports/bin/sshrvd.dart" -o "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME/sshrvd";
+    dart compile exe "$SSHNP_DEV_MODE/packages/sshnoports/bin/activate_cli.dart" -o "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME/at_activate";
+}
+
+# Make a copy of the locally provided archive
+copy_local_archive() {
+  echo "DEV MODE: Installing using local $EXT file: $SSHNP_LOCAL";
+  cp "$SSHNP_LOCAL" "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME.$EXT";
+}
+
+# Download the release archive
+download_archive() {
+  echo "Downloading $BINARY_NAME from $DOWNLOAD";
+  curl -sL "$DOWNLOAD" -o "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME.$EXT";
+  if [ ! -f "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME.$EXT" ]; then
+    echo "Failed to download $BINARY_NAME";
+    echo;
+    echo "Please try again, or download manually from $DOWNLOAD";
+    echo "After downloading manually, run the following command to install:";
+    if [ "$0" == 'bash' ]; then
+      echo "bash -c \"\$(curl https://getsshnpd.noports.com)\" -- -l <path to $EXT file>";
     else
-      echo "Downloading $BINARY_NAME from $DOWNLOAD";
-      curl -sL "$DOWNLOAD" -o "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME.$EXT";
+      echo "  $0 -l <path to $EXT file>";
     fi
+    cleanup
+    exit 1;
+  fi
+}
 
-    if [ ! -f "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME.$EXT" ]; then
-      echo "Failed to download $BINARY_NAME";
-      echo;
-      echo "Please try again, or download manually from $DOWNLOAD";
-      echo "After downloading manually, run the following command to install:";
-      if [ "$0" == 'bash' ]; then
-        echo "bash -c \"\$(curl https://getsshnpd.noports.com)\" -- -l <path to $EXT file>";
-      else
-        echo "  $0 -l <path to $EXT file>";
-      fi
-      cleanup
-      exit 1;
-    fi
-
-    case "$EXT" in
+# Unpack the downloaded / locally provided archive
+unpack_archive() {
+  case "$EXT" in
       zip)
         unzip -qo "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME.$EXT" -d "$HOME_PATH/.atsign/temp/$TEMP_PATH/";
         ;;
@@ -248,23 +314,20 @@ download() {
         ;;
     esac
     mv "$HOME_PATH/.atsign/temp/$TEMP_PATH/sshnp" "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME"; # Rename the extracted folder
-  fi
+}
 
-  if [ -n "$SSHNP_DEV_MODE" ]; then
-    echo "DEV MODE: Installing from local repo: $SSHNP_DEV_MODE";
-    mkdir -p "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME/templates/"
-    mkdir -p "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME/scripts/"
-
-    dart compile exe "$SSHNP_DEV_MODE/packages/sshnoports/bin/sshnp.dart" -o "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME/sshnp";
-    dart compile exe "$SSHNP_DEV_MODE/packages/sshnoports/bin/sshnpd.dart" -o "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME/sshnpd";
-    dart compile exe "$SSHNP_DEV_MODE/packages/sshnoports/bin/sshrv.dart" -o "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME/sshrv";
-    dart compile exe "$SSHNP_DEV_MODE/packages/sshnoports/bin/sshrvd.dart" -o "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME/sshrvd";
-    dart compile exe "$SSHNP_DEV_MODE/packages/sshnoports/bin/activate_cli.dart" -o "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME/at_activate";
-
-
-    cp -R "$SSHNP_DEV_MODE/packages/sshnoports/templates/" "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME/templates/";
-    cp "$SSHNP_DEV_MODE"/packages/sshnoports/scripts/* "$HOME_PATH/.atsign/temp/$TEMP_PATH/$BINARY_NAME";
-  fi
+# Get the main binaries (branches based on the source: download/local/repo)
+get_main_binaries() {
+   if [ -n "$SSHNP_DEV_MODE" ]; then
+    build_dart_binaries
+   else
+    if [ -n "$SSHNP_LOCAL" ]; then
+      copy_local_archive
+    else
+      download_archive
+    fi
+    unpack_archive
+   fi
 }
 
 # Place the actual sshnp binary
@@ -287,11 +350,8 @@ restart_service() {
   killall -q -u "$SSHNP_USER" -r "$BINARY_NAME$"
 }
 
-# Place custom user based scripts
-setup_service() {
-
-  SSHNPD_SERVICE_BINARY_PATH="$HOME_PATH/.local/bin/$BINARY_NAME$CLIENT_ATSIGN";
-  # = is used as the delimiter to avoid escaping / in the path
+# Setup the custom service script part of the service setup
+setup_service_script() {
   if [ "$SSHNP_OP" = 'rename' ] && ! [ -f "$SSHNPD_SERVICE_BINARY_PATH" ]; then
     echo "Error: trying to rename service, but service binary not found";
     exit 1;
@@ -310,7 +370,11 @@ setup_service() {
     echo "Renaming $OLD_DEVICE_NAME to $SSHNP_DEVICE_NAME"
     sed -i "s/\"$OLD_DEVICE_NAME\"/\"$SSHNP_DEVICE_NAME\"/g" "$SSHNPD_SERVICE_BINARY_PATH"
   fi
+}
 
+
+# Setup the cron job part of the service setup
+setup_service_job() {
   SSHNP_CRON_SCHEDULE="@reboot";
   if command -v tmux >/dev/null; then
     SSHNPD_SERVICE_MECHANISM="tmux";
@@ -340,9 +404,10 @@ setup_service() {
       echo "Installed cron job: '$LOGROTATE'";
     fi
   fi
+}
 
-  SERVICE_LIST_FILE="$HOME_PATH/.$BINARY_NAME/.service_list";
-
+# Setup the service list entry part of the service setup
+setup_service_entry() {
   if [ ! -f "$SERVICE_LIST_FILE" ]; then
     touch "$SERVICE_LIST_FILE";
   fi
@@ -375,31 +440,46 @@ setup_service() {
   else
     echo "Service entry added: $BINARY_NAME$CLIENT_ATSIGN $SSHNPD_SERVICE_MECHANISM";
   fi
+}
 
+# Place custom user based scripts
+setup_service() {
+  # Files used by the setup functions below
+  SSHNPD_SERVICE_BINARY_PATH="$HOME_PATH/.local/bin/$BINARY_NAME$CLIENT_ATSIGN";
+  SERVICE_LIST_FILE="$HOME_PATH/.$BINARY_NAME/.service_list";
+
+  setup_service_script
+  setup_service_job
+  setup_service_entry
+
+  # Will start the service if needed (determine by the previous setup functions)
   if [ -z "$NO_RUN" ]; then
     echo "Starting $BINARY_NAME$CLIENT_ATSIGN service...";
     eval "$SSHNP_COMMAND &"
   fi
 }
 
+# Install a new sshnpd instance
 do_install() {
   make_dirs
-  download
+  get_main_binaries
   setup_main_binaries
   setup_service
   cleanup
   echo; echo "Installation complete!";
 }
 
+# Perform an update of all the sshnpd on the local user
 do_update() {
   make_dirs
-  download
+  get_main_binaries
   setup_main_binaries
   cleanup
   echo; echo "Update complete!";
   restart_service
 }
 
+# Perform a rename of an sshnpd instance
 do_rename() {
   setup_service
   echo; echo "Rename complete!";
@@ -407,6 +487,14 @@ do_rename() {
 
 # Wrapping install steps prevents issues caused by interrupting the download
 main () {
+  parse_requirements
+  REQ_ERRORS=$(check_requirements)
+  if [ -n "$REQ_ERRORS" ] ; then
+    echo "System failed to meet installation requirements"
+    echo "$REQ_ERRORS"
+    exit 1
+  fi
+  validate_args
   parse_env
   case "$SSHNP_OP" in
     install)
