build: back out the concept of a 'beta' directory in the distribution

diff --git a/packages/dart/sshnoports/buildArchive b/packages/dart/sshnoports/buildArchive
--- a/packages/dart/sshnoports/buildArchive
+++ b/packages/dart/sshnoports/buildArchive
@@ -10,7 +10,6 @@ echo
 
 rm -rf build/sshnp build/sshnp.zip build/sshnp.tgz
 mkdir -p build/sshnp/web/admin
-mkdir -p build/sshnp/beta/web/admin
 
 dart pub get || exit 1
 
@@ -28,7 +27,7 @@ echo "$(date) : Compilation complete"
 echo "Compiling policy binaries"
 echo "Compiling npp_file.dart to npp_file"; dart compile exe --verbosity error bin/npp_file.dart -o build/sshnp/npp_file &
 ln -s build/sshnp/npp_file build/sshnp/npa_file
-echo "Compiling npp_atserver (BETA)"; dart compile exe --verbosity error bin/npp_atserver.dart -o build/sshnp/beta/npp_atserver &
+echo "Compiling npp_atserver (BETA)"; dart compile exe --verbosity error bin/npp_atserver.dart -o build/sshnp/npp_atserver &
 
 wait
 echo "$(date) : Compilation complete"
@@ -36,7 +35,7 @@ echo "$(date) : Compilation complete"
 echo "Building admin API and webapp - BETA";
 pushd ../../../apps/admin/admin_api || exit 1
 dart pub get || exit 1
-echo "Compiling admin_api"; dart compile exe --verbosity error bin/np_admin.dart -o "${packageDir}/build/sshnp/beta/np_admin" || exit 1
+echo "Compiling admin_api"; dart compile exe --verbosity error bin/np_admin.dart -o "${packageDir}/build/sshnp/np_admin" || exit 1
 wait
 cd ../webapp || exit 1
 echo "Building admin webapp"
@@ -55,7 +54,7 @@ cp -r bundles/shell/* build/sshnp/
 cp LICENSE build/sshnp
 
 echo "$(date) : Copying webapp files - BETA"
-cp -r ../../../apps/admin/webapp/dist/* build/sshnp/beta/web/admin/
+cp -r ../../../apps/admin/webapp/dist/* build/sshnp/web/admin/
 
 cd build
 
