test: e2e_all: various enhancements / fixes etc - de-duped some code into common_functions.include.sh - backup authorized_keys when commencing, restore at end - disable ssh-agent during these tests (it is super annoying to have these ephemeral keys be added to ssh-agent) - added `--foreground` to `timeout` command so that Ctrl-C will work during test runs - renamed main entrypoint to 'main.sh' - changed output to say 'N/A' rather than 'IGNORED' when tests are not applicable (e.g. due to version constraints) - added test of the '-u' daemon flag - don't need to sleep at the end now before killing the daemons, because we restore the authorized_keys file from the backup we took when we were starting the test run - updated README

diff --git a/tests/e2e_all/scripts/tests/minus_s_flag b/tests/e2e_all/scripts/tests/minus_s_flag
--- a/tests/e2e_all/scripts/tests/minus_s_flag
+++ b/tests/e2e_all/scripts/tests/minus_s_flag
@@ -6,7 +6,6 @@
 # 3a. Run against a daemon with the -s flag
 #   3b. Verify it succeeds
 
-# shellcheck disable=SC2034
 scriptName=$(basename -- "$0")
 
 if test -z "$testScriptsDir" ; then
@@ -23,10 +22,11 @@ fi
 daemonVersion="$1"
 clientVersion="$2"
 
+if [[ "$clientVersion" != "d:current" ]] || [[ "$daemonVersion" != "d:current" ]]; then
+  exit 50 # test rig interprets this exit status as 'test was not applicable'
+fi
 # 1. Generate a new ssh key
-mkdir -p "$HOME/.ssh"
-chmod go-rwx "$HOME/.ssh"
-ssh-keygen -t ed25519 -q -N '' -f "${identityFilename}" -C "$commitId"<<< y >/dev/null 2>&1
+generateNewSshKey
 
 # logInfo "Client version : $c_type : $c_major.$c_minor.$c_patch"
 clientBinaryPath=$(getPathToBinariesForTypeAndVersion "$clientVersion")
@@ -34,24 +34,24 @@ clientBinaryPath=$(getPathToBinariesForTypeAndVersion "$clientVersion")
 #
 # v4 feature set, default client flags
 
-# 1. All client versions since 5 require the '-x' flag in order to output the
-# ssh command rather than just forking to the ssh inline.
-# 2. sshnp since 5.x also requires '--no-ad' and '--no-et' flags
-# since those features are enabled by default from v5
+# - All client versions since 5 require the '-x' flag in order to output the
+#   ssh command rather than just forking to the ssh inline.
+# - sshnp since 5.x also requires '--no-ad' and '--no-et' flags,
+#   since those features are enabled by default from v5
 if [[ $(versionIsAtLeast "$clientVersion" "d:5.0.0") == "true" ]] ; then
-  v5Flags="-x --no-ad --no-et"
+  extraFlags="-x --no-ad --no-et"
 fi
 
 # 2a. Run sshnp against a daemon without the -s flag, with that new key
 #   2b. Verify it fails
-deviceName=$(getNoFlagsDeviceNameForCommitIDTypeAndVersion "$commitId" "$daemonVersion" )
+deviceName=$(getDeviceNameNoFlags "$commitId" "$daemonVersion" )
 l1="$clientBinaryPath/sshnp -f $clientAtSign -d $deviceName -i $identityFilename"
 l2=" -t $daemonAtSign -h $srvAtSign -u $remoteUsername"
 l4=" --root-domain $atDirectoryHost"
-l5=" ${v5Flags}"
+l5=" ${extraFlags}"
 sshnpCommand="$l1 $l2 $l3 $l4 $l5 -s ${identityFilename}.pub"
 
-echo "$(iso8601Date) | Executing $sshnpCommand" | tee -a "$(getReportFile)"
+echo "$(iso8601Date) | Executing $sshnpCommand"
 sshCommand=$($sshnpCommand)
 sshnpExitStatus=$?
 
@@ -61,43 +61,42 @@ sshnpExitStatus=$?
 # - 4.x clients, and 5.x clients against 4.x daemons will show success to this point
 #   so let's try the ssh which will fail
 if (( sshnpExitStatus != 0 )); then
-  echo "$(iso8601Date) | $scriptName: sshnp with new key failed as expected" | tee -a "$(getReportFile)"
+  logInfo "$scriptName: sshnp with new key failed as expected" | tee -a "$(getReportFile)"
 else
-  # shellcheck disable=SC2016
-  sshCommand=${sshCommand} 'echo $(date) $(whoami) $(hostname) TEST PASSED'
+  echo "$(iso8601Date) | Executing $sshCommand"
 
-  # shellcheck disable=SC2016
-  echo "$(iso8601Date) | Executing $sshCommand" 'echo $(date) $(whoami) $(hostname) TEST PASSED' | tee -a "$(getReportFile)"
-  # shellcheck disable=SC2016
   # shellcheck disable=SC2091
-  $sshCommand 'echo $(date) $(whoami) $(hostname) TEST PASSED'
+  $(getTestSshCommand "$sshCommand")
   exitStatus=$?
+
   if (( exitStatus == 0 )); then
     # It should have failed
-    echo "$(iso8601Date) | $scriptName: sshnp with new key did not fail as expected" | tee -a "$(getReportFile)"
+    logError "$scriptName: sshnp with new key did not fail as expected" | tee -a "$(getReportFile)"
     exit 1
   else
-    echo "$(iso8601Date) | $scriptName: sshnp with new key failed as expected" | tee -a "$(getReportFile)"
+    logInfo "$scriptName: sshnp with new key failed as expected" | tee -a "$(getReportFile)"
   fi
 fi
 
 
 # 3a. Run against a daemon with the -s flag
 #   3b. Verify it succeeds
-deviceName="${deviceName}f"
+deviceName=$(getDeviceNameWithFlags "$commitId" "$daemonVersion" )
 l1="$clientBinaryPath/sshnp -f $clientAtSign -d $deviceName -i $identityFilename"
 l2=" -t $daemonAtSign -h $srvAtSign -u $remoteUsername"
 l4=" --root-domain $atDirectoryHost"
-l5=" ${v5Flags}"
+l5=" ${extraFlags}"
 sshnpCommand="$l1 $l2 $l3 $l4 $l5 -s ${identityFilename}.pub"
 
-echo "$(iso8601Date) | Executing $sshnpCommand" | tee -a "$(getReportFile)"
+echo "$(iso8601Date) | Executing $sshnpCommand"
 sshCommand=$($sshnpCommand)
-# shellcheck disable=SC2016
-sshCommand=${sshCommand}
+sshnpExitStatus=$?
+if (( sshnpExitStatus != 0 )); then
+  exit $sshnpExitStatus
+fi
 
-# shellcheck disable=SC2016
-echo "$(iso8601Date) | Executing $sshCommand 'echo \$(date) \$(whoami) \$(hostname) TEST PASSED'" | tee -a "$(getReportFile)"
-# shellcheck disable=SC2016
+echo "$(iso8601Date) | Executing $sshCommand"
+
 # shellcheck disable=SC2091
-$sshCommand 'echo $(date) $(whoami) $(hostname) TEST PASSED'
+$(getTestSshCommand "$sshCommand")
+
diff --git a/tests/e2e_all/scripts/tests/shared/sshnp_with_et_and_rvd_auth b/tests/e2e_all/scripts/tests/shared/sshnp_with_et_and_rvd_auth
--- a/tests/e2e_all/scripts/tests/shared/sshnp_with_et_and_rvd_auth
+++ b/tests/e2e_all/scripts/tests/shared/sshnp_with_et_and_rvd_auth
@@ -18,7 +18,7 @@ clientVersion="$2"
 sshClient="$3"
 
 # logInfo "Daemon version : $d_type : $d_major.$d_minor.$d_patch"
-deviceName=$(getNoFlagsDeviceNameForCommitIDTypeAndVersion "$commitId" "$daemonVersion" )
+deviceName=$(getDeviceNameWithFlags "$commitId" "$daemonVersion" )
 
 # logInfo "Client version : $c_type : $c_major.$c_minor.$c_patch"
 clientBinaryPath=$(getPathToBinariesForTypeAndVersion "$clientVersion")
@@ -31,29 +31,34 @@ clientBinaryPath=$(getPathToBinariesForTypeAndVersion "$clientVersion")
 # 1. All client versions since 5 require the '-x' flag in order to output the
 # ssh command rather than just forking to the ssh inline.
 if [[ $(versionIsAtLeast "$clientVersion" "d:5.0.0") == "true" ]] ; then
-  v5Flags="-x"
+  extraFlags="-x"
 fi
 
 # Daemon versions prior to 5 do not support rvd authentication nor end-to-end encryption
 if [[ $(versionIsLessThan "$daemonVersion" "d:5.0.0") == "true" ]]; then
-  echo "Daemon version $daemonVersion is less than required version for this test d:5:0:0 - will ignore this test" >> $(getReportFile)
-  exit 50
+  exit 50 # test rig interprets this exit status as 'test was not applicable'
 fi
 
 # Client versions prior to 5 do not support rvd authentication nor end-to-end encryption
 if [[ $(versionIsLessThan "$clientVersion" "d:5.0.0") == "true" ]]; then
-  echo "Client version $clientVersion is less than required version for this test d:5:0:0 - will ignore this test" >> $(getReportFile)
-  exit 50
+  exit 50 # test rig interprets this exit status as 'test was not applicable'
 fi
 
 l1="$clientBinaryPath/sshnp -f $clientAtSign -d $deviceName -i $identityFilename"
 l2=" -t $daemonAtSign -h $srvAtSign -u $remoteUsername"
 l3=" --ssh-client $sshClient"
 l4=" --root-domain $atDirectoryHost"
-l5=" ${v5Flags}"
-command="$l1 $l2 $l3 $l4 $l5"
+l5=" ${extraFlags}"
+sshnpCommand="$l1 $l2 $l3 $l4 $l5 -s ${identityFilename}.pub"
 
-echo "$(iso8601Date) | Executing $command" | tee -a "$(getReportFile)"
+echo "$(iso8601Date) | Executing $sshnpCommand" | tee -a "$(getReportFile)"
+sshCommand="$($sshnpCommand)"
+sshnpExitStatus=$?
+if (( sshnpExitStatus != 0 )); then
+  exit $sshnpExitStatus
+fi
+
+echo "$(iso8601Date) | Executing $sshCommand" | tee -a "$(getReportFile)"
 
 # shellcheck disable=SC2091
-$($command) <<< 'echo $(date) $(whoami) $(hostname) TEST PASSED'
+$(getTestSshCommand "$sshCommand")
